// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _extauth from "./ext/auth";
import type * as _cal from "./cal";
export type $TitleStatus = {
  "UPCOMING": $.$expr_Literal<$TitleStatus>;
  "PENDING": $.$expr_Literal<$TitleStatus>;
  "WATCHING": $.$expr_Literal<$TitleStatus>;
  "UNFINISHED": $.$expr_Literal<$TitleStatus>;
  "FINISHED": $.$expr_Literal<$TitleStatus>;
} & $.EnumType<"default::TitleStatus", ["UPCOMING", "PENDING", "WATCHING", "UNFINISHED", "FINISHED"]>;
const TitleStatus: $TitleStatus = $.makeType<$TitleStatus>(_.spec, "ceb95d2b-1244-11ef-a827-712081eb39ab", _.syntax.literal);

export type $TitleType = {
  "MOVIE": $.$expr_Literal<$TitleType>;
  "SERIES": $.$expr_Literal<$TitleType>;
} & $.EnumType<"default::TitleType", ["MOVIE", "SERIES"]>;
const TitleType: $TitleType = $.makeType<$TitleType>(_.spec, "cea29ed9-1244-11ef-b672-87a20433753c", _.syntax.literal);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "followers": $.LinkDesc<$Follower, $.Cardinality.Many, {}, false, true,  false, false>;
  "avatar": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "username": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, true, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "status": $.PropertyDesc<$TitleStatus, $.Cardinality.One, false, false, false, true>;
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, true, false,  false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "<addedBy[is Hive]": $.LinkDesc<$Hive, $.Cardinality.Many, {}, false, false,  false, false>;
  "<followed[is Follower]": $.LinkDesc<$Follower, $.Cardinality.Many, {}, false, false,  false, false>;
  "<follower[is Follower]": $.LinkDesc<$Follower, $.Cardinality.Many, {}, false, false,  false, false>;
  "<addedBy": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<followed": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<follower": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {username: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {email: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {identity: {__element__: _extauth.$Identity, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $User = $.makeType<$User>(_.spec, "cea77369-1244-11ef-a5e7-77aa817531a6", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $CurrentUserλShape = $.typeutil.flatten<$UserλShape & {
}>;
type $CurrentUser = $.ObjectType<"default::CurrentUser", $CurrentUserλShape, null, [
  ...$User['__exclusives__'],
]>;
const $CurrentUser = $.makeType<$CurrentUser>(_.spec, "ceb8cfbd-1244-11ef-9a29-e527ac9b3081", _.syntax.literal);

const CurrentUser: $.$expr_PathNode<$.TypeSet<$CurrentUser, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CurrentUser, $.Cardinality.Many), null);

export type $FollowerλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "followed": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "follower": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "<followers[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<followers[is CurrentUser]": $.LinkDesc<$CurrentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<followers": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Follower = $.ObjectType<"default::Follower", $FollowerλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {follower: {__element__: $User, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },followed: {__element__: $User, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Follower = $.makeType<$Follower>(_.spec, "d66b7f65-1244-11ef-a1b0-0bd7960d0458", _.syntax.literal);

const Follower: $.$expr_PathNode<$.TypeSet<$Follower, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Follower, $.Cardinality.Many), null);

export type $HiveλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "rating": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "status": $.PropertyDesc<$TitleStatus, $.Cardinality.One, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "finishedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "isFavorite": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "title": $.LinkDesc<$Title, $.Cardinality.One, {}, true, false,  false, false>;
  "addedBy": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Hive = $.ObjectType<"default::Hive", $HiveλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {title: {__element__: $Title, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Hive = $.makeType<$Hive>(_.spec, "ceb974b9-1244-11ef-abb9-9de112553eb8", _.syntax.literal);

const Hive: $.$expr_PathNode<$.TypeSet<$Hive, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Hive, $.Cardinality.Many), null);

export type $SeasonλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "title": $.LinkDesc<$Title, $.Cardinality.One, {}, false, false,  false, false>;
  "season": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "date": $.PropertyDesc<_cal.$local_date, $.Cardinality.One, false, false, false, false>;
  "episodes": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "<seasons[is Title]": $.LinkDesc<$Title, $.Cardinality.Many, {}, false, false,  false, false>;
  "<seasons": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Season = $.ObjectType<"default::Season", $SeasonλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {title: {__element__: $Title, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },season: {__element__: _std.$int32, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Season = $.makeType<$Season>(_.spec, "d7083a72-1244-11ef-95fe-fb5dc9c0a1ce", _.syntax.literal);

const Season: $.$expr_PathNode<$.TypeSet<$Season, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Season, $.Cardinality.Many), null);

export type $TitleλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "seasons": $.LinkDesc<$Season, $.Cardinality.Many, {}, false, true,  false, false>;
  "type": $.PropertyDesc<$TitleType, $.Cardinality.One, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "genres": $.PropertyDesc<$.ArrayType<_std.$int32>, $.Cardinality.One, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "date": $.PropertyDesc<_cal.$local_date, $.Cardinality.One, false, false, false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "poster": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "posterBlur": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tmdbId": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "imdbId": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "rating": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "<title[is Hive]": $.LinkDesc<$Hive, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "<title[is Season]": $.LinkDesc<$Season, $.Cardinality.Many, {}, false, false,  false, false>;
  "<title": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Title = $.ObjectType<"default::Title", $TitleλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {tmdbId: {__element__: _std.$int32, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },type: {__element__: $TitleType, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Title = $.makeType<$Title>(_.spec, "cea2b14b-1244-11ef-8e05-cfde8e6e6b05", _.syntax.literal);

const Title: $.$expr_PathNode<$.TypeSet<$Title, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Title, $.Cardinality.Many), null);

const $default__globals: {  CurrentUser: _.syntax.$expr_Global<
              // "default::CurrentUser",
              $CurrentUser,
              $.Cardinality.AtMostOne
              >} = {  CurrentUser: _.syntax.makeGlobal(
              "default::CurrentUser",
              $.makeType(_.spec, "ceb8cfbd-1244-11ef-9a29-e527ac9b3081", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { TitleStatus, TitleType, $User, User, $CurrentUser, CurrentUser, $Follower, Follower, $Hive, Hive, $Season, Season, $Title, Title };

type __defaultExports = {
  "TitleStatus": typeof TitleStatus;
  "TitleType": typeof TitleType;
  "User": typeof User;
  "CurrentUser": typeof CurrentUser;
  "Follower": typeof Follower;
  "Hive": typeof Hive;
  "Season": typeof Season;
  "Title": typeof Title;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "TitleStatus": TitleStatus,
  "TitleType": TitleType,
  "User": User,
  "CurrentUser": CurrentUser,
  "Follower": Follower,
  "Hive": Hive,
  "Season": Season,
  "Title": Title,
  "global": $default__globals
};
export default __defaultExports;
