// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _extauth from "./ext/auth";
import type * as _cal from "./cal";
export type $TitleStatus = {
  "UPCOMING": $.$expr_Literal<$TitleStatus>;
  "PENDING": $.$expr_Literal<$TitleStatus>;
  "WATCHING": $.$expr_Literal<$TitleStatus>;
  "UNFINISHED": $.$expr_Literal<$TitleStatus>;
  "FINISHED": $.$expr_Literal<$TitleStatus>;
} & $.EnumType<"default::TitleStatus", ["UPCOMING", "PENDING", "WATCHING", "UNFINISHED", "FINISHED"]>;
const TitleStatus: $TitleStatus = $.makeType<$TitleStatus>(_.spec, "d76718fd-0702-11ef-8f1d-13b90def468d", _.syntax.literal);

export type $TitleType = {
  "MOVIE": $.$expr_Literal<$TitleType>;
  "SERIES": $.$expr_Literal<$TitleType>;
} & $.EnumType<"default::TitleType", ["MOVIE", "SERIES"]>;
const TitleType: $TitleType = $.makeType<$TitleType>(_.spec, "d749c984-0702-11ef-a022-e53dab41908e", _.syntax.literal);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, false, false,  false, false>;
  "avatar": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "username": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<createdBy[is List]": $.LinkDesc<$List, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "d74f3c7f-0702-11ef-853c-8fe0ed0cc245", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $CurrentUserλShape = $.typeutil.flatten<$UserλShape & {
}>;
type $CurrentUser = $.ObjectType<"default::CurrentUser", $CurrentUserλShape, null, [
  ...$User['__exclusives__'],
]>;
const $CurrentUser = $.makeType<$CurrentUser>(_.spec, "d76631bd-0702-11ef-beeb-4dcfff6c9fd6", _.syntax.literal);

const CurrentUser: $.$expr_PathNode<$.TypeSet<$CurrentUser, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CurrentUser, $.Cardinality.Many), null);

export type $ListλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "createdBy": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "title": $.LinkDesc<$Title, $.Cardinality.One, {}, false, false,  false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "rating": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "status": $.PropertyDesc<$TitleStatus, $.Cardinality.One, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $List = $.ObjectType<"default::List", $ListλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $List = $.makeType<$List>(_.spec, "d7672c63-0702-11ef-b21a-9909a2dda5d8", _.syntax.literal);

const List: $.$expr_PathNode<$.TypeSet<$List, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($List, $.Cardinality.Many), null);

export type $TitleλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "genres": $.PropertyDesc<$.ArrayType<_std.$int32>, $.Cardinality.One, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "date": $.PropertyDesc<_cal.$local_date, $.Cardinality.One, false, false, false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "imdbId": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "poster": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "posterBlur": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "tmdbId": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "type": $.PropertyDesc<$TitleType, $.Cardinality.AtMostOne, false, false, false, false>;
  "updated": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "<title[is List]": $.LinkDesc<$List, $.Cardinality.Many, {}, false, false,  false, false>;
  "<title": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Title = $.ObjectType<"default::Title", $TitleλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Title = $.makeType<$Title>(_.spec, "d749e65e-0702-11ef-881f-2b319d6b6580", _.syntax.literal);

const Title: $.$expr_PathNode<$.TypeSet<$Title, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Title, $.Cardinality.Many), null);

const $default__globals: {  CurrentUser: _.syntax.$expr_Global<
              // "default::CurrentUser",
              $CurrentUser,
              $.Cardinality.AtMostOne
              >} = {  CurrentUser: _.syntax.makeGlobal(
              "default::CurrentUser",
              $.makeType(_.spec, "d76631bd-0702-11ef-beeb-4dcfff6c9fd6", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { TitleStatus, TitleType, $User, User, $CurrentUser, CurrentUser, $List, List, $Title, Title };

type __defaultExports = {
  "TitleStatus": typeof TitleStatus;
  "TitleType": typeof TitleType;
  "User": typeof User;
  "CurrentUser": typeof CurrentUser;
  "List": typeof List;
  "Title": typeof Title;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "TitleStatus": TitleStatus,
  "TitleType": TitleType,
  "User": User,
  "CurrentUser": CurrentUser,
  "List": List,
  "Title": Title,
  "global": $default__globals
};
export default __defaultExports;
