name: CI

on: [push, pull_request]

env:
  TMDB_API_KEY: "example-api-key"
  NEXT_PUBLIC_BASE_URL: "https://example.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Prebuild EdgeDB
        run: bun prebuild

      - name: Format
        run: bun format

      - name: Lint
        run: bun lint

      - name: Typecheck
        run: bun typecheck

      - name: Verify Working Environment Variables
        run: |
          echo "TMDB_API_KEY: $TMDB_API_KEY"
          echo "NEXT_PUBLIC_BASE_URL: $NEXT_PUBLIC_BASE_URL"
